### ISSUE TITLE
NoneType' object has no attribute 'shape

### ISSUE THREAD

**Issue by jaspreetbaidwan** [lucataco/cog-faceswap#3]
Hi lucataco

I've been using this replicate API (https://replicate.com/lucataco/faceswap) in PHP, and it has been working well. However, for the past few days, it sometimes works and sometimes gives an error: 'NoneType' object has no attribute 'shape' when I send an images path from my domain. Images from other domains work fine. I also talked with my server, and they said everything is fine on their end, and they also cleared all caches.

It seems that the API does not read my image content sometimes. Is there any attribute in the API that I can pass to clear the cache of my images?

**Comment by lucataco** [comment]
This usually happens if no face is found in the image

**Comment by jaspreetbaidwan** [comment]
Yes, but sometimes it works for the same images. For example, one day those images might give a "NoneType" error, but when I check the next day with the same images, it works.

On my local machine, I also created the Python code and tried the same images, but those images worked fine.
